### PR TITLE
Changeable TX FIFO settings in makefile

### PR DESCRIPTION
**Pull request by bwintermann**
Add variables to adapt the TX FIFO settings in the Makefile as well. By default set to the previously hardcoded values.

### CODE REVIEW

**Comment by Mellich** [comment]
Please also document and explain the new variables in the README (as long as we have no other place for documentation).

**Comment by bwintermann** [comment]
Added it to the Readme. Should be usable just as the RX variants, unless there is a specific reason to not let the TX depth and thresholds be changeable @papeg?

**Comment by Mellich** [comment]
I think we didn't publish these variables because we didn't see the need to modify them. You need to set the RX thresholds and sizes to prevent data loss caused by the flow control latency. However, `TX_FIFO_DEPTH` may only be used to prevent stalls on the sending side. With the HLS tools, it is much cleaner to use the build in AXI FIFOs of the link configuration, which doesn't require changes in our Aurora kernel.
So something like this to set the fifo depth to 256:

```
stream_connect=issue_1.data_output:aurora_hls_1.tx_axis:256
```

The full and empty signals for this FIFO are not used because TREADY of the AXI stream is used instead for flow control from the user kernel side. So you may modify them with `TX_FIFO_PROG_FULL` and `TX_FIFO_PROG_EMPTY`, but they shouldn't have much effect in the current setup.

So you don't have a specific use case for these variables?
In that case, we should add a more detailed explanation to the documentation to clarify this for future us.

**Comment by bwintermann** [comment]
I wanted to change these variables since I have a stalling issue in my project, which could maybe be solved by adjusting the FIFO depths throughout the designs - and since it doesn't modify any existing code, I thought putting it upstream might be a good change, just in case it's ever needed.

**Comment by Mellich** [comment]
Agree. Much better than undocumented magic numbers in the code. I will merge this for now since it shouldn't affect functionality. I am quite confident that the full/empty variables do nothing in that case, but @papeg should re-check and document it accordingly since he has the better overview.

**Pull request merged**
